name: animated_otp_input
description: A customizable, animated, and accessible OTP input widget for Flutter with advanced theming, error handling, and paste detection.
version: 1.0.5
homepage: https://github.com/altwaireb/animated_otp_input
repository: https://github.com/altwaireb/animated_otp_input
issue_tracker: https://github.com/altwaireb/animated_otp_input/issues
license: MIT
topics:
- otp
- input
- pin
- authentication
- flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  mockito: ^5.4.2
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
